# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1a72b914cad385ebced0c708045bf084"
name = "Ecs WhatsApp Chat Dev"
application_url = "https://ecs-whatsapp-chat-dev.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://whatsapp-mern-backend-sidn.onrender.com/api/shopify/webhook"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,write_products,read_themes"

[auth]
redirect_urls = [
  "https://ecs-whatsapp-chat-dev.onrender.com/auth/callback",
  "https://ecs-whatsapp-chat-dev.onrender.com/auth/shopify/callback",
  "https://ecs-whatsapp-chat-dev.onrender.com/api/auth/callback"
]


[product.metafields.app.demo_info]
type = "single_line_text_field"
name = "Demo Source Info"
description = "Tracks products created by the Shopify app template for development"

  [product.metafields.app.demo_info.access]
  admin = "merchant_read_write"

[metaobjects.app.example]
name = "Example"
description = "An example metaobject definition created by this template"

  [metaobjects.app.example.access]
  admin = "merchant_read_write"

[metaobjects.app.example.fields.title]
name = "Title"
type = "single_line_text_field"
required = true

[metaobjects.app.example.fields.description]
name = "Description"
type = "multi_line_text_field"
